// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    login: function(req, res) {
      console.log("login");
      if (req.isAuthenticated()) {
        return res.redirect("/");
      } else {
        return res.render("login");
      }
    },
    loginSuccess: function(req, res) {
      console.log("loginSuccess");
      return res.redirect("/");
    },
    logout: function(req, res) {
      console.log("logout");
      req.logout();
      return res.redirect("/");
    },
    ensureAuthenticated: function(req, res, next) {
      console.log("ensureAuthenticated");
      if (req.isAuthenticated()) {
        return next();
      }
      return res.redirect("/");
    },
    ensureAuthenticatedAjax: function(req, res, next) {
      console.log("ensureAuthenticatedAjax");
      if (req.isAuthenticated()) {
        return next();
      }
      return res.send(401);
    }
  };

}).call(this);
