// Generated by CoffeeScript 1.7.1
(function() {
  var financeDataModel, schoolDataModel;

  schoolDataModel = require("../models/schoolModel.js");

  financeDataModel = require("../models/financeModel.js");

  module.exports = {
    index: function(req, res) {
      return res.render("index", {
        title: "Feed Dem Kids"
      });
    },
    profile: function(req, res) {
      return schoolDataModel.findById(req.params.id, function(err, doc) {
        return financeDataModel.findOne({
          zip: doc.zip
        }, function(err, result) {
          if (err) {
            res.send(err);
          }
          console.log(result.snapPercent);
          return res.render("school-profile", {
            school: doc,
            finance: result
          });
        });
      });
    },
    find: function(req, res) {
      return res.render("find");
    },
    getRandomSchools: function(req, res) {
      var count, schools, _results;
      schools = [];
      count = 0;
      _results = [];
      while (count < 3) {
        count++;
        _results.push(schoolDataModel.getRandomDoc(function(err, result) {
          schools.push(result);
          if (schools.length === 3) {
            return res.send({
              schools: schools
            });
          }
        }));
      }
      return _results;
    },
    search: function(req, res) {
      return schoolDataModel.find({
        name: new RegExp(req.query.input, "i")
      }, function(err, results) {
        return res.send({
          schools: results,
          query: req.query.input
        });
      });
    }
  };

}).call(this);
