// Generated by CoffeeScript 1.7.1
(function() {
  var financeDataModel, schoolDataModel;

  schoolDataModel = require("../models/schoolModel.js");

  financeDataModel = require("../models/financeModel.js");

  module.exports = {
    index: function(req, res) {
      return res.render("index", {
        title: "Feed Dem Kids"
      });
    },
    profile: function(req, res) {
      return schoolDataModel.findById(req.params.id, function(err, doc) {
        return financeDataModel.findOne({
          zip: doc.zip
        }, function(err, result) {
          if (err) {
            res.send(err);
          }
          console.log(result.ssiPercent, result.cpaPercent);
          return res.render("school-profile", {
            school: doc,
            finance: result
          });
        });
      });
    },
    find: function(req, res) {
      return res.render("find");
    }
  };

}).call(this);
