// Generated by CoffeeScript 1.7.1
(function() {
  var stripe;

  stripe = require("stripe")("sk_test_BQokikJOvBiI2HlWgH4olfQ2");

  module.exports = {
    checkoutForm: function(req, res) {
      console.log("checkout form");
      return res.render("checkout");
    },
    checkoutSuccess: function(req, res) {
      var charge, stripeToken;
      console.log("checkout success", stripe);
      stripeToken = req.body.stripeToken;
      return charge = stripe.charges.create({
        amount: 1000,
        currency: "usd",
        card: stripeToken,
        description: "payinguser@example.com"
      }, function(err, charge) {
        if (err && err.type === "StripeCardError") {
          res.send("The card has been declined");
        }
        return res.send("success: " + JSON.stringify(charge));
      });
    }
  };

}).call(this);
