// Generated by CoffeeScript 1.7.1
(function() {
  var financeDataModel, schoolDataModel, userModel;

  schoolDataModel = require("../models/schoolModel.js");

  userModel = require("../models/userModel.js");

  financeDataModel = require("../models/financeModel.js");

  module.exports = {
    profile: function(req, res) {
      var myID;
      myID = req.params.id ? req.params.id : "531f6d9c77f4d4be42dee22f";
      return userModel.findOne({
        _schoolId: myID
      }, function(err, result) {
        if (err) {
          return console.log(err);
        } else {
          return schoolDataModel.findById(myID, function(err, doc) {
            var JSONdoc;
            JSONdoc = doc.toJSON({
              virtuals: true
            });
            console.log(JSONdoc);
            return res.render("school-admin", {
              school: JSONdoc,
              userSchool: result ? result.profile : null
            });
          });
        }
      });
    },
    update: function(req, res) {
      return res.send(req.body.formData);
    }
  };

}).call(this);
